
--  Plain email with an attachment


INSERT INTO `EMAIL_HEADER` (`REC_ID`, `EMAIL_USER_ID`, `EMAIL_ID`, `EMAIL_UID`, `EMAIL_THREAD_ID`, `EMAIL_MSG_ID`, `EMAIL_PARENT_ID`, `EMAIL_REF_ID`, `EMAIL_DATE`, `EMAIL_TIME`, `EMAIL_FOLDER_TOP`, `EMAIL_FOLDER_SUB`, `EMAIL_FOLDER_LVL`, `EMAIL_SUBJECT`, `EMAIL_FROM`, `EMAIL_SIZE`, `EMAIL_READ_FLAG`, `EMAIL_TAGGED_FLAG`, `EMAIL_PRIVATE_FLAG`, `EMAIL_REPLIED_FLAG`, `EMAIL_FORWARD_FLAG`, `EMAIL_DELETED_FLAG`, `EMAIL_HTML_FLAG`, `EMAIL_ATTACH_FLAG`, `EMAIL_USER_OUT_FLAG`, `EMAIL_LINKED_FLAG`, `EMAIL_OPP_ID`, `EMAIL_QUOTE_ID`, `EMAIL_JOB_ID`, `EMAIL_PLAN_ID`, `EMAIL_PO_ID`, `EMAIL_PRIORITY`, `EMAIL_TO`, `EMAIL_CC`, `EMAIL_BCC`, `EMAIL_DISPLAY_NAME`, `EMAIL_ARCHIVE`, `EMAIL_ARCHIVE_FOLDER`, `EMAIL_FOLLOWUP_FLAG`, `EMAIL_PRIV_TEAM`, `EMAIL_LAST_UPDATE`, `EMAIL_CONTENT_PLAIN`, `EMAIL_ERROR_MSG`, `EMAIL_STAGE_ID`, `EMAIL_REPLY_TO`) VALUES
(446848, 1, 496673, 'AAMkAGEwNTA0YjdlLTM3ZTItNDljNy04ZTYwLTJhMGU1NWQ4YzE0OABGAAAAAAD_PFSL-JSjQp156EUPIvWLBwCnd4_T2fvqQpH9DHPKly7KAAAAAAEMAACnd4_T2fvqQpH9DHPKly7KAAUXgnwQAAA=', 'AAQkAGEwNTA0YjdlLTM3ZTItNDljNy04ZTYwLTJhMGU1NWQ4YzE0OAAQAAVwmyuO8vdJreKYRTAYnbM=', 'cf26cd16-7ac7-46ef-aca2-d379e961cb86@indeadesignsystems.com', 'e33b9b30-70ed-4223-8839-cd72ce4f2227@indeadesignsystems.com', 'c4934812-72cf-4f5b-ae39-b68763b482b1@indeadesignsystems.com', '2025-01-03', '10:52:27', 'inbox', '', 0, 'Admin communication with an attachment', 'muralime@indeadesignsystems.com', '', 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 'System Admin <systemadmin@repfabric.com>', '', '', 'Murali Meleth <muralime@indeadesignsystems.com>', 0, '', 0, 0, '2025-01-03 10:55:02', 'Hi Admin,\r\n\r\nThis is a simple communication related to the job in progress to let you know that everything is going as planned.  Please review the attached.\r\n\r\nWill keep you posted on the daily progress status.\r\n\r\nRegards,\r\n\r\nBob\r\n\r\n\r\n______________________________\r\nSr. Software Manager\r\nIndea Design Systems Pvt. Ltd.\r\n\r\nT: +91 94487 82071\r\nW: https://indeadesignsystems.com<https://indeadesignsystems.com/>\r\n\r\n\r\n204, 2nd Floor, Crystal Arc\r\nBalmatta Road, Hampankatta\r\nMangaluru, Karnataka, India', '0', NULL, '');


-- Content 

INSERT INTO `EMAIL_CONTENT` (`REC_ID`, `EMAIL_CONT_EMAIL_ID`, `EMAIL_CONT_CONTENT`) VALUES
(448977, 496673, '<html><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"></head><body><p>Hi Admin, <br></p><p>This is a simple communication related to the job in progress to let you know that everything is going as planned.&nbsp; Please review the attached.<br></p><p>Will keep you posted on the daily progress status.</p><p>Regards,</p><p>Bob<br></p><p><br></p><div class=\"moz-signature\"><p style=\"line-height:100%; margin-bottom:0.5cm\"><font face=\"Liberation Sans, sans-serif\"><font size=\"2\" style=\"font-size:10pt\"><i>______________________________</i></font></font> <br><font face=\"Liberation Sans, sans-serif\">Sr. Software Manager</font><font face=\"Liberation Sans, sans-serif\"><font size=\"2\" style=\"font-size:10pt\"><br></font></font><font face=\"Liberation Sans, sans-serif\">Indea Design Systems Pvt. Ltd.</font></p><p style=\"line-height:100%; margin-bottom:0cm\"><font face=\"Liberation Sans, sans-serif\"><font size=\"2\" style=\"font-size:10pt\"><i>T: +91 94487 82071<br>W: <a href=\"https://indeadesignsystems.com/\" class=\"moz-txt-link-freetext\">https://indeadesignsystems.com</a><br></i></font></font><br></p><p style=\"line-height:100%; margin-bottom:0cm\"><font face=\"Liberation Sans, sans-serif\"><font size=\"2\" style=\"font-size:10pt\"><i>204, 2nd Floor, Crystal Arc<br>Balmatta Road, Hampankatta<br>Mangaluru, Karnataka, India</i></font></font></p></div></body></html>');


-- Attachment

INSERT INTO `EMAIL_ATTACHMENT` (`REC_ID`, `EMAIL_ATTA_EMAIL_ID`, `EMAIL_ATTA_NAME`, `EMAIL_ATTA_LOCATION`) VALUES
(50824, 496673, '496673-Screenshot from 2024-12-18 17-30-21.png', 'attachment/1/0/');

